version: '3'
services:
  php:
    image: dfossacecchi/php-8.2-fpm:1.2
    build:
      context: ./docker/php
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    user: 'www-data'
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      DB_HOST: postgres
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: nE3mkCYlg61ZI8Ii
      COMPOSER_MEMORY_LIMIT: -1
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
  nginx:
    image: dfossacecchi/nginx:1.0
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_MULTIPLE_DATABASES: "app,app:app_test,app"
      POSTGRES_USER: app
      POSTGRES_PASSWORD: nE3mkCYlg61ZI8Ii
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
      - ./docker/postgres/init-db:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  postgres_data:
