name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .env
        run: cp .env.ci .env

      - name: Init Environment
        run: make init

      - name: Run tests
        run: make test
