name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve composer cache
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest

      - name: Save composer cache
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ hashFiles('**/composer.lock') }}

      - name: Setup .env
        run: cp .env.ci .env

      - name: Init Environment
        run: make up

      - name: Run tests
        run: make test


